add_test( ReplyTest.ToBufferOKReply /usr/src/projects/mrjk-web-server/build_coverage/bin/reply_test [==[--gtest_filter=ReplyTest.ToBufferOKReply]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReplyTest.ToBufferOKReply PROPERTIES WORKING_DIRECTORY /usr/src/projects/mrjk-web-server/tests)
add_test( ReplyTest.ToBufferBADReply /usr/src/projects/mrjk-web-server/build_coverage/bin/reply_test [==[--gtest_filter=ReplyTest.ToBufferBADReply]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReplyTest.ToBufferBADReply PROPERTIES WORKING_DIRECTORY /usr/src/projects/mrjk-web-server/tests)
add_test( ReplyTest.ToBufferOtherReply /usr/src/projects/mrjk-web-server/build_coverage/bin/reply_test [==[--gtest_filter=ReplyTest.ToBufferOtherReply]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReplyTest.ToBufferOtherReply PROPERTIES WORKING_DIRECTORY /usr/src/projects/mrjk-web-server/tests)
add_test( ReplyTest.ReplyToBuffersTest /usr/src/projects/mrjk-web-server/build_coverage/bin/reply_test [==[--gtest_filter=ReplyTest.ReplyToBuffersTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReplyTest.ReplyToBuffersTest PROPERTIES WORKING_DIRECTORY /usr/src/projects/mrjk-web-server/tests)
add_test( ReplyTest.StockRepliesToStringOtherRequest /usr/src/projects/mrjk-web-server/build_coverage/bin/reply_test [==[--gtest_filter=ReplyTest.StockRepliesToStringOtherRequest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReplyTest.StockRepliesToStringOtherRequest PROPERTIES WORKING_DIRECTORY /usr/src/projects/mrjk-web-server/tests)
set( reply_test_TESTS ReplyTest.ToBufferOKReply ReplyTest.ToBufferBADReply ReplyTest.ToBufferOtherReply ReplyTest.ReplyToBuffersTest ReplyTest.StockRepliesToStringOtherRequest)
