if(EXISTS "/usr/src/projects/mrjk-web-server/build_coverage/reply_test[1]_tests.cmake")
  include("/usr/src/projects/mrjk-web-server/build_coverage/reply_test[1]_tests.cmake")
else()
  add_test(reply_test_NOT_BUILT reply_test_NOT_BUILT)
endif()
